# Generated by Django 3.1.6 on 2021-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PFirstName', models.CharField(default=' ', max_length=50)),
                ('pLastName', models.CharField(default=' ', max_length=50)),
                ('PEmail', models.CharField(default=' ', max_length=120)),
                ('PCity', models.CharField(default=' ', max_length=150)),
                ('PState', models.CharField(default=' ', max_length=150)),
            ],
        ),
    ]
