# Generated by Django 3.1.6 on 2021-05-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210515_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='paddress',
            new_name='PAddress',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='pLastName',
            new_name='PLastName',
        ),
    ]
